services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    restart: always
    build:
      context: .
      dockerfile: src/AuctionApi/Dockerfile              
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=false
    networks:
      - auction-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - auction-network

  worker-auction:
    container_name: worker-auction
    restart: always
    build:
      context: .           
      dockerfile: src/Auction.Worker/Auction.Worker/Dockerfile
    #deploy:
      #replicas: 2
    environment:
      - MT_LICENSE=Community   
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=false
    depends_on:
      - rabbitmq         
    networks:
      - auction-network

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
    networks:
      - auction-network
    
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - auction-network

# 1. Definir a rede no escopo global
networks:
  auction-network:
    driver: bridge